export enum ErrorMessajes {
  ALREADY_USER,
  USER_NOT_FOUND,
  PASSWORD_INCORRECT,
  NO_TOKEN_PROVIDED,
  NO_BEARER_TOKEN,
  INVALID_TOKEN,
  JWT_ERROR,
  ERROR_REGISTER,
  ERROR_LOGIN,
  INTERNAL_SERVER_ERROR
}