export enum ErrorMessajes {
  ALREADY_USER = 'ALREADY_USER',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  PASSWORD_INCORRECT = 'PASSWORD_INCORRECT',
  NO_TOKEN_PROVIDED = 'NO_TOKEN_PROVIDED',
  NO_BEARER_TOKEN = 'NO_BEARER_TOKEN',
  INVALID_TOKEN = 'INVALID_TOKEN',
  JWT_ERROR = 'JWT_ERROR',
  ERROR_REGISTER = 'ERROR_REGISTER',
  ERROR_LOGIN = 'ERROR_LOGIN',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
}
